[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "12.18.3"
  REACT_APP_CONTEXT = "production"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
